const express = require('express');
const authnticateUser = require('../MiddleWares/auth');
const moneyController = require('../Controllers/moneyController');
const expenseRoutes = express.Router();
expenseRoutes.get('/MainHome', authnticateUser, moneyController.getExpenseMainHomePage);
expenseRoutes.get('/expenseMain', authnticateUser, moneyController.getExpenseMainPage);
expenseRoutes.post('/post-expense', authnticateUser, authnticateUser, moneyController.addExpense);
expenseRoutes.get('/viewExpenses', authnticateUser, moneyController.getExpensesViewPage);
expenseRoutes.get('/viewExpensesData', authnticateUser, moneyController.getExpensesData);
expenseRoutes.post('/deleteExpensedata', authnticateUser, moneyController.deleteExpenseData);
expenseRoutes.post('/update-expense', authnticateUser, moneyController.updateExpense);
expenseRoutes.get('/leaderBoardPage', authnticateUser, moneyController.getLeaderBoardPage);
expenseRoutes.get('/viewLeaderBoardData', authnticateUser, moneyController.getLeaderBoardData);
expenseRoutes.get('/viewMonetaryData', authnticateUser, moneyController.getViewMonetaryPage);
expenseRoutes.get('/viewYearlyExpensesData', authnticateUser, moneyController.getYearlyExpensesData);
expenseRoutes.post('/download', authnticateUser, moneyController.downloadExpense);
expenseRoutes.get('/getDownloadUrl', authnticateUser, moneyController.getDownloadUrl);
expenseRoutes.get('/viewReportExpensesData', authnticateUser, moneyController.viewReportExpensesData);
expenseRoutes.get('/viewExpenseGraph', authnticateUser, moneyController.getExpenseGraph);
expenseRoutes.get('/getSavingsData', authnticateUser, moneyController.getSavingsData);

module.exports = expenseRoutes;